--Task 1.2

SELECT *
FROM EMPLOYEE
WHERE SURNAME LIKE '%on%'; 

--Task 1.3

SELECT *
FROM EMPLOYEE
WHERE SALARY > 2800;

--Task 1.4

SELECT *
FROM EMPLOYEE
WHERE BID = 4647;

--Task 1.5

SELECT *
FROM EMPLOYEE
WHERE SUPERVISORID = ANY
(SELECT EMPID
 FROM EMPLOYEE
 WHERE title LIKE 'Manager%');
 
 --Task 1.6
 
Select *
FROM CUSTOMER c
INNER JOIN CUSTOMERACCOUNT ca
    on c.CUSTID = ca.CUSTID
INNER JOIN ACCOUNT a
    on ca.ACCNUM = a.ACCNUM
WHERE a.BID = 4647 AND a.BALANCE > 2000;

--Task 1.7

SELECT * 
FROM EMPLOYEE
WHERE BID = 4647 AND SALARY > ANY
(SELECT salary
 FROM EMPLOYEE
 WHERE CONCAT(FIRSTNAME, SURNAME) LIKE '%JohnSmith%');
 
 --Task 1.8
 
 Select *
FROM CUSTOMER c
INNER JOIN CUSTOMERACCOUNT ca
    on c.CUSTID = ca.CUSTID
INNER JOIN ACCOUNT a
    on ca.ACCNUM = a.ACCNUM
WHERE a.OPENDATE < '01-JUN-2014';

--Task 1.9

SELECT MAX(BALANCE)
FROM CUSTOMER c
INNER JOIN CUSTOMERACCOUNT ca
    on c.CUSTID = ca.CUSTID
INNER JOIN ACCOUNT a
    on ca.ACCNUM = a.ACCNUM;
    
--1.10


